### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by fycarman** [AntiCheatPE/AntiCheatPE#1]
- [x] Make a To-Do list
- [x] Speed hack detection
- [x] Fly hack detection
- [x] Jump hack detection
- [x] Make this plugin fully customizable

**Comment by fycarman** [comment]
Done!
