### ISSUE TITLE
To-Do list for AntiCheat 2.0.0

### ISSUE THREAD

**Issue by fycarman** [AntiCheatPE/AntiCheatPE#5]
- [ ] Fix bugs (if found)
- [ ] Add an api for developers
- [ ] Add admin commands
- [ ] Add hacks severity level
- [ ] Make these new things user-customizable
- [ ] more Cheat detections
